In [ ]:
#1. Load the Academic Performance dataset in data frame object.
#2. Check null values in the dataset.
#3. Check missing values in dataset  and replace the null values with standard null value NaN
#4.  Replace the missing  value of Math Score with Mean Value
#5.  Replace the missing value of Reading Score with standard deviation
#6.  Replace the missing value of place with common value "Nashik"

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/StudentsPerformanceTest1.csv')
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [ ]:
df.isnull()
# Step 2: Check for null values in the dataset

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False
8,False,False,False,False,False,False,True

In [ ]:
df.isnull().sum()

gender                   0
math score               1
reading score            0
writing score            1
Placement Score          1
placement offer count    0
Region                   1
dtype: int64

In [ ]:
df.replace('', np.nan, inplace=True)
df
# Step 3: Standardize missing values (if not already None or NaN)

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,NaN

In [ ]:
#math_mean = df['math score'].mean()
#df['math score'].fillna(math_mean, inplace=True)
# Step 4: Replace missing values in 'math_score' with mean#



df['math score'] = pd.to_numeric(df['math score'], errors='coerce')

# Calculate the mean of 'math score'
math_mean = df['math score'].mean()

# Replace missing values with the mean
df['math score'].fillna(math_mean, inplace=True)

print("Updated 'math score' column:\n", df['math score'])

Updated 'math score' column:
 0    72.000000
1    69.000000
2    90.000000
3    47.000000
4    52.285714
5    71.000000
6    12.000000
7    52.285714
8     5.000000
Name: math score, dtype: float64

<ipython-input-5-55a245ca0452>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['math score'].fillna(math_mean, inplace=True)

In [ ]:
# Step 5: Replace missing values in 'reading_score' with standard deviation
#reading_std = df['reading score'].std()
#df['reading score'].fillna(reading_std, inplace=True)


 #Convert 'reading score' to numeric, coercing errors to NaN
df['reading score'] = pd.to_numeric(df['reading score'], errors='coerce')

# Calculate the standard deviation of 'reading score'
reading_std = df['reading score'].std()

# Replace missing values with the standard deviation
df['reading score'].fillna(reading_std, inplace=True)

print("Updated 'reading score' column:\n", df['reading score'])

Updated 'reading score' column:
 0    72.000000
1    90.000000
2    95.000000
3    57.000000
4    78.000000
5    16.782218
6    44.000000
7    65.000000
8    77.000000
Name: reading score, dtype: float64

<ipython-input-6-f61fdda1f89a>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reading score'].fillna(reading_std, inplace=True)

In [ ]:
# Step 6: Replace missing values in 'place' with the common value "Nashik"
df['Region'].fillna('Nashik', inplace=True)
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune
5,female,71,Na,78.0,70.0,4,na
6,male,12,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5,77,89.0,55.0,0,Nashik